### ISSUE TITLE
在OC上用不了会报错

### ISSUE THREAD

**Issue by devilon** [fitomad/iOS-Bubble-Transition#1]
在OC上用不了会报错，
bubble.startingPoint ; bubble.transitionMode;
这两个属性没法使用，
不用以上两个属性，运行会报错在 94行  
let frame: CGRect = self.frameForBubbleWithSize(originalSize, start: self.startingPoint)

请作者去解决，谢！

**Comment by fitomad** [comment]
Modify initializer to set `startingPoint`property at _upper left corner_ by default.

**Comment by devilon** [comment]
@interface BubbleTransition : NSObject

@property (nonatomic) CGPoint startingPoint;
@property (nonatomic, strong) UIColor \* _Nullable bubbleColor;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;

@end

桥接OC后，bubble.transitionMode这个属性还是不能用啊？？？

请作者帮忙去解决，谢！

**Comment by fitomad** [comment]
Could you share a full example?

**Comment by devilon** [comment]
[TestBubbleTransition.zip](https://github.com/fitomad/iOS-Bubble-Transition/files/445158/TestBubbleTransition.zip)

**Comment by fitomad** [comment]
Download the new TransitionMode version

:+1:

**Comment by devilon** [comment]
Crash in line 145, when i using TransitionModeDismiss property.

self.bubble.frame = self.frameForBubbleWithSize(originalSize, start: startingPoint)  
[TestBubbleTransition.zip](https://github.com/fitomad/iOS-Bubble-Transition/files/449174/TestBubbleTransition.zip)
